### ISSUE TITLE
SemVer releases

### ISSUE THREAD

**Issue by sagikazarmark** [segmentio/ksuid#17]
Now that the Go ecosystem started to lean towards using semantic versioning, using git tags for this package might help people utilizing the new way in their applications. Also, gives the impression that this package is production ready.

What do you think?

**Comment by sagikazarmark** [comment]
Ping :)

**Comment by achille-roussel** [comment]
Sounds good, I'll tag a 1.0.0 release 👍

**Comment by sagikazarmark** [comment]
Wonderful, thanks a lot!
