### ISSUE TITLE
ksuid.Parse sometimes panics instead of returning an error

### ISSUE THREAD

**Issue by olivoil** [segmentio/ksuid#25]
When parsing a 27-long string that is not a valid ksuid, it will panic instead of returning an error. For instance `ksuid.Parse("aaaaaaaaaaaaaaaaaaaaaaaaaaa")` will panic.

The signature `func Parse(s string) (KSUID, error)` seems to imply that any string that can't successfully be parsed should return an error, and not panic. I think that should be the expected behavior at least.

Maybe the fix would be to update `Parse` or `fastDecodeBase62` to not panic? In any case, if there's a valid reason for wanting it to panic, the documentation should be updated so it doesn't come as a surprise.

**Comment by achille-roussel** [comment]
Thanks for reporting, this is definitely unexpected, I’ll send a PR to address later today.
