### ISSUE TITLE
Is KSUID safe to use as a Login Session Id

### ISSUE THREAD

**Issue by FarooqKhan** [segmentio/ksuid#29]
The readme says "KSUIDs use 128-bits of pseudorandom data" I am wondering why PRNG and not a TRNG? My actual question is would KSUID be safe to use as a Login Session Id?

**Comment by achille-roussel** [comment]
The wording may not be fully accurate, by default the implementation uses /dev/urandom (or similar depending on the platform) which is suitable for cryptographic purposes.

**Comment by achille-roussel** [comment]
Long story short, you can use them as session IDs ;)
