### ISSUE TITLE
cmd template should use text/template to avoid escaping

### ISSUE THREAD

**Issue by tmthrgd** [segmentio/ksuid#37]
The ksuid command uses `html/template` [here](https://github.com/segmentio/ksuid/blob/a39015a56de643f2ddfeb1237299fa562243d910/cmd/ksuid/main.go#L8) instead of `text/template`. `html/template` escapes the output and corrupts it.

This is the result of running the ksuid command:
```
$ ksuid -f template -t '{{ .Time }}: {{ .Payload }}' $(ksuid)
2018-10-17 00:04:57 &#43;1030 ACDT: 956449DBD1047A4E0F7963973073EEF2
```

`&#43;` should be `+`.

**Comment by achille-roussel** [comment]
You’re correct, this looks like an oversight. 

Would you be able to send a pull request to fix the issue?
