### ISSUE TITLE
How it works with MySQL 

### ISSUE THREAD

**Issue by shwetasynoverge** [segmentio/ksuid#41]
I want to know how we can use KSUID with MySQL ? Also if yes how indexing would work

**Comment by achille-roussel** [comment]
We've used KSUIDs as primary keys in MySQL database, ether using their base62 representation or their binary format. The column type should be `varbinary(27)` or `varbinary(20)` depending on the approach you take. The advantage of using the base62 representation is it enables copy/pasting values when composing queries _manually_.

Let me know if that helps answer your question.

**Comment by shwetasynoverge** [comment]
Thanks for your prompt reply. And can you please explain me that how indexing for ksuid works in MySQL?

**Comment by shwetasynoverge** [comment]
Also one more question :
Is it possible to generate KSUID directly through MYSQL ?
like for example we have "SELECT UUID()" ?

**Comment by achille-roussel** [comment]
It'll work just like indexing other byte sequences, a lexicographic comparison will work just fine with KSUID (in both base62 and binary representations).

I'm not aware of any MySQL function that generate a KSUID, we generate them client-side when constructing queries.

**Comment by shwetasynoverge** [comment]
Thanks a lot
