### ISSUE TITLE
Is it possible to generate KSUID from SQL?

### ISSUE THREAD

**Issue by derkan** [segmentio/ksuid#43]
Hi,
To set `DEFAULT` value for an `PK` of table, I wonder if has anyone tried to generate a valid `ksuid` value by using SQL.

For example for UUIDv4, we can [generate default value](https://stackoverflow.com/questions/12505158/generating-a-uuid-in-postgres-for-insert-statement) if `uuid-ossp` extension is not installed for PostrgreSQL as:

```sql
`CREATE TABLE IF NOT EXISTS table (
   id VARCHAR(36) DEFAULT md5(random()::text || clock_timestamp()::text)::uuid  NOT NULL,
....
```
Of course it'll be better to generate from application but, I it makes simpler to add default value for manual interactions with tables.

Has anyone tried to develop an SQL function to geneate `ksuid`?

**Comment by daleobrien** [comment]
It's certainly possible, here's what I have done https://github.com/daleobrien/sql-ksuid

**Comment by derkan** [comment]
thank you, now the missing part is found! 👏
