### ISSUE TITLE
Why is a cryptographically-strong pseudorandom number generator required?

### ISSUE THREAD

**Issue by aggsol** [segmentio/ksuid#9]
Uniqueness and randomness are important. A Mersenne Twister would be enough, wouldn't it?

**Comment by rbranson** [comment]
Currently it uses the same random input as Google's UUID library: https://github.com/google/uuid/blob/master/uuid.go#L187

It's certainly possible to switch to using the normal rand library (which I believe uses a Mersenne Twister) and using the CSPRNG as a seed. The only question is: why?

**Comment by aggsol** [comment]
@rbranson Speed is the only reason. I am looking at a C++ implementation and just wanted to be sure I understand the spec. Depending on the requirements if you need 100 KSUID/s or 1M KSUID/s.

**Comment by achille-roussel** [comment]
@rbranson I was curious so I checked the throughput difference, here are some numbers:
```
BenchmarkNew-4            	 1000000	      1226 ns/op	       0 B/op	       0 allocs/op
BenchmarkNewNonCrypto-4   	20000000	       117 ns/op	       0 B/op	       0 allocs/op
```
Most of the time is spent in syscall.Read when using the crypto/rand source.

**Comment by rbranson** [comment]
@aggsol this was addressed in https://github.com/segmentio/ksuid/pull/12. tl;dr we support both methods now, default is (slow but maybe more correct?) reading directly from /dev/urandom.
